### PR TITLE
Manifest v3 

### PR DESCRIPTION
**Pull request by SpritePW**
Update extension to manifest version 3, use FCM instead of polling Twitch and Youtube APIs constantly.

### CODE REVIEW

**Comment by scowalt** [comment]
@GACastro95 LMK if you need me to do anything with the Chrome extension I have listed on the Chrome web store. Right now I think the version is quite old. I can delist it or whatever if you're making your own. Cheers!

**Comment by SpritePW** [comment]
@scowalt Hey Scott, yeah if you could delist the extension on the Chrome web store that would be great.

**Comment by scowalt** [comment]
> @scowalt Hey Scott, yeah if you could delist the extension on the Chrome web store that would be great.

Done. I unpublished on my end. For some reason I still see my extension - https://chrome.google.com/webstore/detail/newlegacyinc/ejmobeklchnhloamlgdaklmcebhfboab

LMK if it doesn't get unlisted and I can figure out what's going on

**Comment by scowalt** [comment]
@GACastro95 there we go! The old extension is now Private (delisted) https://chrome.google.com/webstore/detail/newlegacyinc/ejmobeklchnhloamlgdaklmcebhfboab

**Pull request merged**
